### ISSUE TITLE
Incorrect escaping of some character sequences in string values.

### ISSUE THREAD

**Issue by craigmiskell-gitlab** [kgiszczak/tomlib#2]
If a string value contains the sequence `#$`, this is incorrectly rendered to the output with an escaped #, which is invalid TOML and cannot be parsed by a compliant parser (including tomlib):

```
irb(main):001:0> require 'tomlib'
=> true
irb(main):002:0>  configuration = {bar: {foo: 'Aa#$298gXsqK9876'} }
=> {:bar=>{:foo=>"Aa\#$298gXsqK9876"}}
irb(main):003:0> puts Tomlib.dump(configuration)
[bar]
foo = "Aa\#$298gXsqK9876"                               
=> nil                                                  
irb(main):004:0> Tomlib.load(Tomlib.dump(configuration))
(irb):4:in `load': line 2: bad escape char (Tomlib::ParseError)
```

This comes from the use of [inspect](https://github.com/kgiszczak/tomlib/blob/master/lib/tomlib/dumper.rb#L140) on the String, which escapes per *Ruby* rules (where `#$` is shorthand for a global variable interpolation, so the # must be escaped by inspect), not per [TOML](https://toml.io/en/v0.3.0#string) rules.  There are other similar character sequences that cause the same issue (e.g. `#{` and possibly others).

**Comment by WarheadsSE** [comment]
👋 As TOML strings _nearly_ perfectly compliant with [JSON strings (RFC8529)](https://www.rfc-editor.org/rfc/rfc8259.html#section-7)*, there are several possible approaches that could be taken.

The problem lies in [value.inspect](https://github.com/kgiszczak/tomlib/blob/master/lib/tomlib/dumper.rb#L138-L141
)
- [TOML v1.0.0](https://toml.io/en/v1.0.0#string) string specification contains the list of special characters to be concerned of. JSON is _close_, but with `/` added.
- [tomlrb](https://github.com/fbernier/tomlrb) (MIT) implements a [dedicated `StringUtils`](https://github.com/fbernier/tomlrb/blob/master/lib/tomlrb/string_utils.rb) class.

For the sake of preserving simplicity and speed, it is likely best to have a helper specifically introduced to handle the encoding. This could be in the Ruby side _or_ the C side.

**Comment by kgiszczak** [comment]
Thanks for looking into it, having an encoder sounds like a good approach, I'll get to it in a couple of days.

**Comment by kgiszczak** [comment]
Thank you for reporting this issue, I released a new version that should take care of it.
If there is anything else you need let me know.
